#!/bin/sh
#
# This hook is called by "git commit" to prepare 
# the commit log message.
#
# below we intercept the hook to intentionally slow 
# down git's application of cherry-picks during rebase
# todos that can cause collision with a persistent
# .git/index.lock file on slower releasing EFS filesystems.
#
# 1) if .git/index.lock exists ... pause for 1s
# 2) if .git/index.lock persists ... delete it
#
# To enable this hook, rename this file to "prepare-commit-msg"
# To disable this hook, rename this file to "prepare-commit-msg.sample"
# author: Stu Field

FILE=.git/index.lock

if [ -f $FILE ]; then
  echo "\tpausing for 1s ..."
  sleep 1.0
  if [ -f $FILE ]; then
    echo "\tdeleting '$FILE' file ..."
    rm -rf $FILE
  fi
else
  echo "Good news! No '$FILE' file!"
fi
