#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=50'   # cyan
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'    # grey
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=70'   # green
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=80'   # cyan
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=90'   # purple
